require('plugins')
require('options')
require('appearance')
vim.cmd.source('~/.config/nvim/mycommand.vim')
vim.cmd.source('~/.config/nvim/plugconf.vim')
--vim.cmd.source('~/.config/nvim/apperance.vim')
vim.cmd.source('~/.config/nvim/keybindings.vim')
vim.cmd.source('~/.config/nvim/treesitter.lua')
