require('plugins')
require('options')
require('appearance')
require('treesitter')
vim.cmd.source('~/.config/nvim/mycommand.vim')
vim.cmd.source('~/.config/nvim/plugconf.vim')
vim.cmd.source('~/.config/nvim/keybindings.vim')
